import type { ClientRecord, Interaction, Flag } from "@/types/database";

export const DEMO_STATUSES = [
  { value: "active", label: "Active", color: "bg-emerald-500" },
  { value: "inactive", label: "Inactive", color: "bg-gray-400" },
  { value: "sheltered", label: "Sheltered", color: "bg-blue-500" },
  { value: "unsheltered", label: "Unsheltered", color: "bg-orange-500" },
  { value: "pending", label: "Pending", color: "bg-yellow-500" },
  { value: "assigned", label: "Assigned", color: "bg-purple-500" },
  { value: "follow_up", label: "Follow-up Needed", color: "bg-red-500" },
];

export const STATUS_MAP: Record<string, { label: string; color: string; bg: string }> = {
  active: { label: "Active", color: "text-emerald-700", bg: "bg-emerald-50 border-emerald-200" },
  inactive: { label: "Inactive", color: "text-gray-600", bg: "bg-gray-50 border-gray-200" },
  sheltered: { label: "Sheltered", color: "text-blue-700", bg: "bg-blue-50 border-blue-200" },
  unsheltered: { label: "Unsheltered", color: "text-orange-700", bg: "bg-orange-50 border-orange-200" },
  pending: { label: "Pending", color: "text-yellow-700", bg: "bg-yellow-50 border-yellow-200" },
  assigned: { label: "Assigned", color: "text-purple-700", bg: "bg-purple-50 border-purple-200" },
  follow_up: { label: "Follow-up Needed", color: "text-red-700", bg: "bg-red-50 border-red-200" },
};

export const FLAG_MAP: Record<string, { label: string; color: string; bg: string; icon: string }> = {
  high_risk: { label: "High Risk", color: "text-red-700", bg: "bg-red-50 border-red-300", icon: "⚠️" },
  medical: { label: "Medical Concern", color: "text-orange-700", bg: "bg-orange-50 border-orange-300", icon: "🏥" },
  escalated: { label: "Escalated", color: "text-purple-700", bg: "bg-purple-50 border-purple-300", icon: "🔺" },
  priority: { label: "Priority Follow-Up", color: "text-yellow-700", bg: "bg-yellow-50 border-yellow-300", icon: "⭐" },
  custom: { label: "Custom", color: "text-blue-700", bg: "bg-blue-50 border-blue-300", icon: "🏷️" },
};

export const DEMO_RECORDS: (ClientRecord & { assigned_user?: { full_name: string }; active_flags?: Flag[] })[] = [
  {
    id: "rec_001",
    organization_id: "org_001",
    full_name: "James Mitchell",
    preferred_name: "Jimmy",
    aliases: ["Big Jim", "JMitch"],
    dob: "1978-03-15",
    approximate_age: 46,
    gender: "Male",
    phone: "555-0101",
    email: null,
    org_record_id: "CLT-0042",
    photo_url: null,
    status: "active",
    assigned_user_id: "usr_001",
    assigned_team: "Outreach Team A",
    program: "Street Outreach",
    notes: "Frequent visitor to Penn Station area. Veteran. Declined shelter twice but open to conversation.",
    metadata: { veteran: true, language: "English" },
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-11-20T14:30:00Z",
    assigned_user: { full_name: "Maria Santos" },
    active_flags: [
      {
        id: "flg_001",
        record_id: "rec_001",
        organization_id: "org_001",
        author_id: "usr_001",
        type: "medical",
        label: "Medical Concern",
        description: "Reported leg injury, needs follow-up",
        resolved: false,
        created_at: "2024-11-18T09:00:00Z",
      },
    ],
  },
  {
    id: "rec_002",
    organization_id: "org_001",
    full_name: "Sarah Chen",
    preferred_name: "Sarah",
    aliases: [],
    dob: "1990-07-22",
    approximate_age: 34,
    gender: "Female",
    phone: "555-0102",
    email: "schen@email.com",
    org_record_id: "CLT-0087",
    photo_url: null,
    status: "sheltered",
    assigned_user_id: "usr_002",
    assigned_team: "Housing Team",
    program: "Rapid Rehousing",
    notes: "Placed at Harbor House on 11/10. Doing well. Check-in scheduled for next week.",
    metadata: { housing_voucher: true, language: "English, Mandarin" },
    created_at: "2024-03-20T11:30:00Z",
    updated_at: "2024-11-10T16:00:00Z",
    assigned_user: { full_name: "David Kim" },
    active_flags: [],
  },
  {
    id: "rec_003",
    organization_id: "org_001",
    full_name: "Robert Washington",
    preferred_name: "Bobby",
    aliases: ["Wash", "DC Bob"],
    dob: "1965-11-08",
    approximate_age: 58,
    gender: "Male",
    phone: null,
    email: null,
    org_record_id: "CLT-0023",
    photo_url: null,
    status: "follow_up",
    assigned_user_id: "usr_001",
    assigned_team: "Outreach Team A",
    program: "Street Outreach",
    notes: "Last seen near Harlem. Uses wheelchair. Medical needs. Family contact: sister Linda 555-0199.",
    metadata: { wheelchair: true, veteran: false, language: "English" },
    created_at: "2023-09-05T08:00:00Z",
    updated_at: "2024-11-05T11:00:00Z",
    assigned_user: { full_name: "Maria Santos" },
    active_flags: [
      {
        id: "flg_002",
        record_id: "rec_003",
        organization_id: "org_001",
        author_id: "usr_001",
        type: "high_risk",
        label: "High Risk",
        description: "Medical needs unaddressed, lost contact",
        resolved: false,
        created_at: "2024-11-05T11:00:00Z",
      },
    ],
  },
  {
    id: "rec_004",
    organization_id: "org_001",
    full_name: "Angela Torres",
    preferred_name: "Angie",
    aliases: ["Ang"],
    dob: "1985-04-30",
    approximate_age: 39,
    gender: "Female",
    phone: "555-0104",
    email: null,
    org_record_id: "CLT-0156",
    photo_url: null,
    status: "pending",
    assigned_user_id: "usr_003",
    assigned_team: "Case Management",
    program: "Emergency Shelter",
    notes: "Applied for emergency shelter. Documents being processed. Spanish-speaking preferred.",
    metadata: { language: "Spanish", case_priority: "high" },
    created_at: "2024-11-01T09:00:00Z",
    updated_at: "2024-11-19T10:00:00Z",
    assigned_user: { full_name: "James Park" },
    active_flags: [
      {
        id: "flg_003",
        record_id: "rec_004",
        organization_id: "org_001",
        author_id: "usr_003",
        type: "priority",
        label: "Priority Follow-Up",
        description: "Time-sensitive shelter application",
        resolved: false,
        created_at: "2024-11-01T09:00:00Z",
      },
    ],
  },
  {
    id: "rec_005",
    organization_id: "org_001",
    full_name: "Michael Johnson",
    preferred_name: "Mike",
    aliases: ["MJ", "Big Mike"],
    dob: "1972-09-14",
    approximate_age: 52,
    gender: "Male",
    phone: "555-0105",
    email: null,
    org_record_id: "CLT-0098",
    photo_url: null,
    status: "assigned",
    assigned_user_id: "usr_002",
    assigned_team: "Housing Team",
    program: "Transitional Housing",
    notes: "In transitional housing at Hope Center. Employment search in progress. Very motivated.",
    metadata: { veteran: true, language: "English" },
    created_at: "2024-05-12T14:00:00Z",
    updated_at: "2024-11-15T09:30:00Z",
    assigned_user: { full_name: "David Kim" },
    active_flags: [],
  },
  {
    id: "rec_006",
    organization_id: "org_001",
    full_name: "Lisa Park",
    preferred_name: "Lisa",
    aliases: [],
    dob: "1995-02-18",
    approximate_age: 29,
    gender: "Female",
    phone: "555-0106",
    email: "lpark@email.com",
    org_record_id: "CLT-0201",
    photo_url: null,
    status: "active",
    assigned_user_id: "usr_003",
    assigned_team: "Youth Services",
    program: "Young Adult Program",
    notes: "Recently aged out of foster care. Working part-time. Needs stable housing.",
    metadata: { language: "English, Korean" },
    created_at: "2024-08-22T13:00:00Z",
    updated_at: "2024-11-18T15:00:00Z",
    assigned_user: { full_name: "James Park" },
    active_flags: [],
  },
  {
    id: "rec_007",
    organization_id: "org_001",
    full_name: "Thomas Brown",
    preferred_name: "Tom",
    aliases: ["T-Brown", "Brownie"],
    dob: "1958-12-03",
    approximate_age: 65,
    gender: "Male",
    phone: null,
    email: null,
    org_record_id: "CLT-0015",
    photo_url: null,
    status: "unsheltered",
    assigned_user_id: null,
    assigned_team: null,
    program: null,
    notes: "Long-term street dweller, Brooklyn area near Atlantic Ave. Knows the area well. Cautious of services.",
    metadata: { language: "English" },
    created_at: "2022-06-01T08:00:00Z",
    updated_at: "2024-10-30T12:00:00Z",
    assigned_user: undefined,
    active_flags: [
      {
        id: "flg_004",
        record_id: "rec_007",
        organization_id: "org_001",
        author_id: "usr_001",
        type: "medical",
        label: "Medical Concern",
        description: "Chronic health conditions, needs regular check-ins",
        resolved: false,
        created_at: "2024-10-30T12:00:00Z",
      },
    ],
  },
  {
    id: "rec_008",
    organization_id: "org_001",
    full_name: "David Lee",
    preferred_name: "Dave",
    aliases: [],
    dob: "1988-06-25",
    approximate_age: 36,
    gender: "Male",
    phone: "555-0108",
    email: "dlee@email.com",
    org_record_id: "CLT-0178",
    photo_url: null,
    status: "inactive",
    assigned_user_id: "usr_002",
    assigned_team: "Housing Team",
    program: "Permanent Supportive Housing",
    notes: "Successfully housed 6 months ago. Stable. Periodic check-ins.",
    metadata: { language: "English" },
    created_at: "2023-11-15T10:00:00Z",
    updated_at: "2024-10-01T11:00:00Z",
    assigned_user: { full_name: "David Kim" },
    active_flags: [],
  },
];

export const DEMO_INTERACTIONS: Interaction[] = [
  {
    id: "int_001",
    record_id: "rec_001",
    organization_id: "org_001",
    author_id: "usr_001",
    type: "note",
    content: "Met James at Penn Station. He declined shelter again but accepted warm meal and hygiene kit. Leg appears better. Will follow up next week.",
    tags: ["outreach", "declined-shelter"],
    metadata: { location: "Penn Station" },
    created_at: "2024-11-20T14:30:00Z",
  },
  {
    id: "int_002",
    record_id: "rec_001",
    organization_id: "org_001",
    author_id: "usr_001",
    type: "flag",
    content: "Added medical concern flag — reporting leg injury needs follow-up",
    tags: [],
    metadata: {},
    created_at: "2024-11-18T09:00:00Z",
  },
  {
    id: "int_003",
    record_id: "rec_001",
    organization_id: "org_001",
    author_id: "usr_001",
    type: "note",
    content: "Phone outreach attempt. No answer. Left message with case worker contact info.",
    tags: ["phone", "no-answer"],
    metadata: {},
    created_at: "2024-11-12T10:15:00Z",
  },
  {
    id: "int_004",
    record_id: "rec_001",
    organization_id: "org_001",
    author_id: "usr_002",
    type: "status_change",
    content: "Status updated from 'pending' to 'active'",
    tags: [],
    metadata: { from: "pending", to: "active" },
    created_at: "2024-11-01T08:00:00Z",
  },
  {
    id: "int_005",
    record_id: "rec_002",
    organization_id: "org_001",
    author_id: "usr_002",
    type: "placement",
    content: "Placed at Harbor House shelter. Room 214. Intake completed successfully. All documents submitted.",
    tags: ["shelter", "placement"],
    metadata: { location: "Harbor House", room: "214" },
    created_at: "2024-11-10T16:00:00Z",
  },
  {
    id: "int_006",
    record_id: "rec_002",
    organization_id: "org_001",
    author_id: "usr_002",
    type: "referral",
    content: "Referred to job training program at Workforce Center. Contact: Dana Hill 555-0200.",
    tags: ["employment", "referral"],
    metadata: {},
    created_at: "2024-11-08T13:30:00Z",
  },
];

export const DEMO_TEAM = [
  { id: "usr_001", full_name: "Maria Santos", role: "worker", avatar: null },
  { id: "usr_002", full_name: "David Kim", role: "supervisor", avatar: null },
  { id: "usr_003", full_name: "James Park", role: "worker", avatar: null },
  { id: "usr_current", full_name: "Alex Rivera", role: "admin", avatar: null },
];

export const DEMO_STATS = {
  total_records: 247,
  active_records: 89,
  sheltered: 43,
  follow_up_needed: 28,
  active_flags: 15,
  interactions_today: 12,
};
